= Ansible Playbook for Fuse Online Foundation course - Customization Lab

== Using the Playbook

* Install Ansible on your local PC.
* Download this playbook to your local PC.
* Change working directory to `<fuse_online_lab_assets_dir>/playbook`
* Login to your remote OpenShift environment from your local PC:
+
----
oc login master.<guid>.opentlc.openshift.com -u <opentlc_login_id>
----
+
* Run the script `install.sh`
* Verify using either the OpenShift Management Console or `oc` command tool, that the REST services have been deployed.

== Playbook overview

* This is playbook helps to setup a RESTful service environment using these tasks:
** Create a cluster quota.
** Creates a new project in an OpenShift environment.
** Assigns appropriate privileges to the user account.
** Deploy a date service microservice to the project.
** Expose the microservice using a route.

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you
 need to define to control the deployment of your workload.

* You can modify any of these default values by adding
`-e"variable_name=variable_value"` to the command line

=== Deploy the project

Set up the following environmental variables in your PC environment.

----
TARGET_HOST="bastion.<env-id>.openshift.opentlc.com"
OCP_USERNAME="<opentlc-id>-redhat.com"
WORKLOAD="ocp-workload-restservices"
GUID=<guid>

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
                 -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
                 -e"ansible_ssh_user=ec2-user" \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_username=${OCP_USERNAME}" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"guid=${GUID}" \
                    -e"ocp_user_needs_quota=true" \
                    -e"ocp_apps_domain=apps.rhpds.openshift.opentlc.com" \
                    -e"ACTION=create"

----

=== Delete the project from your OpenShift environment (for clean-up)

Set the following in your PC environment.

----
TARGET_HOST="bastion.<env-id>.openshift.opentlc.com"
OCP_USERNAME="<opentlc-id>-redhat.com"
WORKLOAD="ocp-workload-restservices"
GUID=<guid>

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
                    -e"ansible_ssh_user=ec2-user" \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_username=${OCP_USERNAME}" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"guid=${GUID}" \
                    -e"ACTION=remove"
----
