---
- name: define ocp_project
  set_fact:
    ocp_project: "restservices-{{guid}}"

- name: Create project for workload
  shell: "oc new-project {{ocp_project}}"

- name: Make sure we go back do default project
  shell: "oc project default"

- name: Give ocp_username access to ocp_project
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{ocp_project}}"

- name: Deploy date service microservice
  shell: oc run wfswarm-date-service \
           --image=docker.io/rhtgptetraining/wfswarm-date-service:1.0 \
           --limits='cpu=1000m,memory=512Mi' \
           --requests='cpu=250m,memory=256Mi' \
           --expose=true \
           --port=8080

- name: Expose date service microservice through a route
  shell: oc create route edge wfswarmdatestamproute --service=wfswarm-date-service

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
