---
- name: define ocp_project
  set_fact:
    ocp_project: "fuse-{{guid}}"

- name: Create project for workload
  shell: "oc new-project {{ocp_project}}"

- name: Make sure we go back do default project
  shell: "oc project default"

- name: Create serviceaccount-as-oauthclient
  shell: "oc create -f https://raw.githubusercontent.com/syndesisio/syndesis/master/install/support/serviceaccount-as-oauthclient-restricted.yml -n {{ocp_project}}
"

- name: Create workload template
  shell: "oc create -f https://raw.githubusercontent.com/syndesisio/syndesis/master/install/syndesis.yml -n {{ocp_project}}
"

- name: Create the workload app
  shell: |
      oc new-app syndesis -p ROUTE_HOSTNAME=fuse.{{ocp_project}}.{{ocp_apps_domain}} \
      -p OPENSHIFT_PROJECT={{ocp_project}} \
      -p OPENSHIFT_OAUTH_CLIENT_SECRET=$(oc sa get-token syndesis-oauth-client -n {{ocp_project}}) -n {{ocp_project}}

- name: annotate the project as requested by user
  shell: "oc annotate namespace {{ocp_project}} openshift.io/requester={{ocp_username}} --overwrite"

- name: Give ocp_username access to ocp_project
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{ocp_project}}"

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
