- name: Deploy a workload role on a master host
  hosts: all
  become: false
  gather_facts: False
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
  tags:
    - step007
  roles:
    - role: "{{ ANSIBLE_REPO_PATH }}/roles/{{ocp_workload}}"
      when: ocp_workload is defined
