package com.redhat.insurancequoting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Driver implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer driverID;
	private java.lang.String firstName;
	private java.lang.String lastName;
	private java.lang.Integer age;
	private java.lang.Integer fines;
	private java.lang.Boolean validLicense;

	public Driver() {
	}
	
	public java.lang.Boolean getValidLicense(){
		return this.validLicense;
	}
	public void setValidLicense(java.lang.Boolean validLicense){
		this.validLicense = validLicense;
	}

	public java.lang.Integer getDriverID() {
		return this.driverID;
	}

	public void setDriverID(java.lang.Integer driverID) {
		this.driverID = driverID;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Integer getFines() {
		return this.fines;
	}

	public void setFines(java.lang.Integer fines) {
		this.fines = fines;
	}

	public Driver(java.lang.Integer driverID, java.lang.String firstName,
			java.lang.String lastName, java.lang.Integer age,
			java.lang.Integer fines, java.lang.Boolean validLicense) {
		this.driverID = driverID;
		this.firstName = firstName;
		this.lastName = lastName;
		this.age = age;
		this.fines = fines;
		this.validLicense = validLicense;
	}

}
