package com.redhat.insurancequoting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vehicle implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String maker;
	private java.lang.String model;
	private java.lang.Integer mileage;
	private java.lang.String licensePlate;
	private java.lang.Integer modelYear;

	public Vehicle() {
	}

	public java.lang.String getMaker() {
		return this.maker;
	}

	public void setMaker(java.lang.String maker) {
		this.maker = maker;
	}

	public java.lang.String getModel() {
		return this.model;
	}

	public void setModel(java.lang.String model) {
		this.model = model;
	}

	public java.lang.Integer getMileage() {
		return this.mileage;
	}

	public void setMileage(java.lang.Integer mileage) {
		this.mileage = mileage;
	}

	public java.lang.String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(java.lang.String licensePlate) {
		this.licensePlate = licensePlate;
	}

	public java.lang.Integer getModelYear() {
		return this.modelYear;
	}

	public void setModelYear(java.lang.Integer modelYear) {
		this.modelYear = modelYear;
	}

	public Vehicle(java.lang.String maker, java.lang.String model,
			java.lang.Integer mileage, java.lang.String licensePlate,
			java.lang.Integer modelYear) {
		this.maker = maker;
		this.model = model;
		this.mileage = mileage;
		this.licensePlate = licensePlate;
		this.modelYear = modelYear;
	}

}